name: Build and Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Choose the Java distribution you want (temurin, zulu, etc.)

      - name: Build with Maven
        run: mvn clean package

      - name: Zip the Lambda function
        run: zip -r my-lambda.zip target/*.jar

      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: my-lambda-artifact
          path: my-lambda.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: AWS CLI Setup
        run: |
          pip install awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name my-lambda-function \
            --zip-file fileb://my-lambda.zip
