name: Build and Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      # Verify that the ZIP file is created
      - name: List contents of target directory
        run: ls -la target/

      # Since the ZIP is already built, upload it directly
      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-lambda-artifact
          path: target/aws-lambda-user-1.0-SNAPSHOT-lambda-package.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: AWS CLI Setup
        run: |
          pip install awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name my-lambda-function \
            --zip-file fileb://target/aws-lambda-user-1.0-SNAPSHOT-lambda-package.zip
