name: Build and Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: List contents of target directory
        run: ls -la target/

      # This step is just for logging (optional)
      - name: Find and log ZIP file
        run: |
          ZIP_FILE=$(find target/ -name "*.zip")
          echo "Found ZIP file: $ZIP_FILE"

      # Upload the ZIP file
      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-lambda-artifact
          path: target/*.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: AWS CLI Setup
        run: |
          pip install awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      # Download the artifact
      - name: Download Lambda Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-lambda-artifact

      # Deploy the downloaded ZIP file
      - name: Deploy to AWS Lambda
        run: |
          ZIP_FILE=$(find . -name "*.zip")
          echo "Deploying ZIP file: $ZIP_FILE"
          aws lambda update-function-code \
            --function-name aws-lambda-user1 \
            --zip-file fileb://$ZIP_FILE
