name: Build and Deploy to AWS Lambda

on:
  push:
    branches:
      - main      # For production
      - develop   # For development
      - staging   # For staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: List contents of target directory
        run: ls -la target/

      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-lambda-artifact
          path: target/*.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: AWS CLI Setup
        run: |
          pip install awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      # Download the artifact
      - name: Download Lambda Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-lambda-artifact

      # Choose the correct Lambda function based on the branch
      - name: Set Lambda function name
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "LAMBDA_FUNCTION_NAME=${{ secrets.DEV_LAMBDA_FUNCTION_NAME }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "LAMBDA_FUNCTION_NAME=${{ secrets.STG_LAMBDA_FUNCTION_NAME }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "LAMBDA_FUNCTION_NAME=${{ secrets.PROD_LAMBDA_FUNCTION_NAME }}" >> $GITHUB_ENV
          fi

      # Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        run: |
          ZIP_FILE=$(find . -name "*.zip")
          echo "Deploying ZIP file: $ZIP_FILE to Lambda function: $LAMBDA_FUNCTION_NAME"
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --zip-file fileb://$ZIP_FILE
