name: Build and Deploy to AWS Lambda

# When this workflow should run (on which branch push, pull request, etc.)
on:
  push:
    branches:
      - main  # This will trigger on pushes to the "main" branch

# Define the workflow jobs
jobs:
  build:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    # Steps define the individual tasks that will run in this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Zip the Lambda function
        run: zip -r my-lambda.zip target/*.jar

      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-lambda-artifact
          path: my-lambda.zip

  deploy:
    # Specify that the deploy job depends on the success of the build job
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: AWS CLI Setup
        run: |
          pip install awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name my-lambda-function \
            --zip-file fileb://my-lambda.zip
